# Generated by Django 3.2 on 2022-08-30 19:51

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('empresa_id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa_ruc', models.CharField(max_length=15, unique=True, verbose_name='R.U.C.')),
                ('empresa_rs', models.CharField(max_length=100, unique=True, verbose_name='Razon Social')),
                ('empresa_ubi', models.CharField(max_length=200, verbose_name='Ubicacion')),
                ('empresa_tel', models.CharField(max_length=15, verbose_name='Telefono')),
                ('empresa_mail', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('empresa_pass', models.CharField(max_length=50, verbose_name='Password')),
                ('empresa_web', models.CharField(max_length=75, null=True, verbose_name='Pagina Web')),
                ('empresa_fech_cre', models.DateTimeField(null=True, verbose_name='Fecha de creacion')),
                ('empresa_fech_mod', models.DateTimeField(null=True, verbose_name='Fecha de modificacion')),
                ('empresa_est', models.BooleanField(default=True, verbose_name='Estado de la empresa')),
                ('empresa_usuario_id', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'db_table': 'tbl_empresa',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('paquete_id', models.AutoField(primary_key=True, serialize=False)),
                ('paquete_pre', models.CharField(max_length=20, verbose_name='Precio del paquete')),
                ('paquete_cant_ser', models.IntegerField(default='0')),
                ('paquete_fech_cre', models.DateTimeField(null=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'db_table': 'tbl_paquete',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('servicio_id', models.AutoField(primary_key=True, serialize=False)),
                ('servicio_nom', models.CharField(max_length=100, verbose_name='Servicio')),
                ('servicio_cat_des', models.CharField(choices=[('MONTANA', 'Montaña'), ('DESIERTO', 'Desierto'), ('SELVA', 'Selva')], max_length=100, verbose_name='Categoria Destino')),
                ('servicio_cat_exp', models.CharField(choices=[('AVENTURA', 'Aventura'), ('VIVENCIAL', 'Vivencial'), ('HC', 'Historico Cultural'), ('NATURALEZA', 'Naturaleza'), ('EXCLUSIVO', 'Exclusivo'), ('GASTRONOMIA', 'Gastronomia')], max_length=100, verbose_name='Categoria Experiencia')),
                ('servicio_dep', models.CharField(max_length=50, verbose_name='Departamento')),
                ('servicio_pro', models.CharField(max_length=50, verbose_name='Provincia')),
                ('servicio_dis', models.CharField(max_length=50, verbose_name='Distrito')),
                ('servicio_ubi', models.CharField(max_length=50, null=True, verbose_name='Ubicacion')),
                ('servicio_fech_cre', models.DateTimeField(null=True, verbose_name='Fecha de creacion')),
                ('servicio_fech_mod', models.DateTimeField(null=True, verbose_name='Fecha de modificacion')),
                ('servicio_est', models.BooleanField(default=True, verbose_name='Estado del servicio')),
            ],
            options={
                'db_table': 'tbl_servicio',
            },
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('turista_id', models.AutoField(primary_key=True, serialize=False)),
                ('turista_doc', models.CharField(choices=[('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte'), ('CARNET', 'Carnet de Extranjeria'), ('LIBRETA', 'Libreta Electoral')], max_length=25, verbose_name='Tipo Documento')),
                ('turista_nroDoc', models.CharField(max_length=15, unique=True, verbose_name='Nro documento')),
                ('turista_tel', models.CharField(max_length=15, verbose_name='Telefono')),
                ('turista_sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=50, verbose_name='Sexo')),
                ('turista_pais', models.CharField(max_length=50, verbose_name='Pais de origen')),
                ('turista_ciu', models.CharField(max_length=50, verbose_name='Ciudad de Origen')),
                ('turista_fech_cre', models.DateTimeField(null=True, verbose_name='Fecha de creacion')),
                ('turista_fech_mod', models.DateTimeField(null=True, verbose_name='Fecha de modificacion')),
                ('turista_est', models.BooleanField(default=True, verbose_name='Estado del turista')),
                ('usuario_id', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'db_table': 'tbl_turista',
            },
        ),
        migrations.CreateModel(
            name='ServicioEmpresa',
            fields=[
                ('servicio_empresa_id', models.AutoField(primary_key=True, serialize=False)),
                ('servicio_empresa_est', models.BooleanField(default=True)),
                ('servicio_empresa_des', models.TextField(max_length=500, verbose_name='Descripción')),
                ('servicio_empresa_des2', models.TextField(max_length=500, verbose_name='Descripción2')),
                ('servicio_empresa_car', models.TextField(default='', max_length=200, verbose_name='Caracteristica')),
                ('servicio_empresa_dur', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Duracion del Servicio')),
                ('servicio_empresa_pre', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('servicio_empresa_img', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('servicio_empresa_img_det_1', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image1')),
                ('servicio_empresa_img_det_2', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image2')),
                ('servicio_empresa_img_det_3', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image3')),
                ('empresa_id', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.RESTRICT, related_name='servicioEmpresa', to='api.empresa')),
                ('servicio_id', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.RESTRICT, related_name='servicioEmpresa', to='api.servicio')),
            ],
            options={
                'db_table': 'tbl_servicio_empresa',
            },
        ),
        migrations.CreateModel(
            name='ReservaPago',
            fields=[
                ('reserva_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('reserva_pago_pre', models.CharField(max_length=20, verbose_name='Precio del paquete')),
                ('reserva_pago_conf', models.BooleanField(verbose_name='Confirmacion pago')),
                ('reserva_pago_fech', models.DateTimeField(null=True, verbose_name='Fecha de pago')),
                ('paquete_id', models.ForeignKey(db_column='paquete_id', on_delete=django.db.models.deletion.RESTRICT, related_name='reservaPagoTurista', to='api.paquete')),
                ('turista_id', models.ForeignKey(db_column='turista_id', on_delete=django.db.models.deletion.RESTRICT, related_name='reservaPagoTurista', to='api.turista')),
            ],
            options={
                'db_table': 'tbl_reserva_pago',
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='servicio_empresa_id',
            field=models.ForeignKey(db_column='servicio_empresa_id', on_delete=django.db.models.deletion.RESTRICT, related_name='servicioEmpresa', to='api.servicioempresa'),
        ),
        migrations.CreateModel(
            name='PagoEmpresa',
            fields=[
                ('pago_empresa_id', models.AutoField(primary_key=True, serialize=False)),
                ('pago_empresa_des', models.CharField(max_length=75, verbose_name='Descripcion')),
                ('pago_empresa_mont', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto')),
                ('pago_empresa_com', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comision')),
                ('pago_empresa_fech', models.DateTimeField(null=True, verbose_name='Fecha de creacion')),
                ('pago_empresa_nro', models.CharField(max_length=15, unique=True, verbose_name='Nro Comprobante')),
                ('servicio_empresa_id', models.ForeignKey(db_column='servicio_empresa_id', on_delete=django.db.models.deletion.RESTRICT, related_name='servicio_empresa_pago_empresa', to='api.servicioempresa')),
            ],
            options={
                'db_table': 'tbl_pago_empresa',
            },
        ),
    ]
